'use strict';

const swaggerUi = require('swagger-ui-express');
const swaggerJsdoc = require('swagger-jsdoc');

// disable try out button
const DisableTryItOutPlugin = () => {
  return {
    statePlugins: {
      spec: {
        wrapSelectors: {
          allowTryItOutFor: () => () => false
        }
      }
    }
  };
};
const options = {
  swaggerOptions: {
    plugins: [
      DisableTryItOutPlugin
    ]
  }
};

const spec = {
  swaggerDefinition: {
    openapi: '3.0.0',
    info: {
      title: 'hey-url-challenge-code-node API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
      license: {
        name: 'MIT',
        url: 'https://choosealicense.com/licenses/mit/'
      },
      contact: {
        name: 'Swagger',
        url: 'https://swagger.io',
        email: 'Info@SmartBear.com'
      }
    },
    servers: [
      {
        url: 'http://localhost:5000/'
      }
    ],
    schemes: [
      'https',
      'http'
    ]
  },
  apis: ['./routes/*.js']
};

module.exports = (app) => {
  app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerJsdoc(spec), options));
};
